version: '3'
services:
  db-mega-chat:
    image: postgres:12
    restart: always
    ports:
      - '5444:5432'
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: mega_chat
